#!/bin/bash
cd doc
i=10

echo Clearing the dist directory
rm -rf ../dist
mkdir -p ../dist

echo Resequencing files...
pattern='(^[01234567890 ]*)(.*)'

# count number of files
fc=0
for f in *.md;
do
    let "fc=fc+1"
done
echo $fc
for f in *.md;
do
if [[ "$f" =~ $pattern ]]
then
   #echo matched \'${BASH_REMATCH[0]}\' \'${BASH_REMATCH[1]}\' \'${BASH_REMATCH[2]}\' $1
    echo mv "$f" "$i ${BASH_REMATCH[2]}" 2>/dev/null
    let "i=i+10"
fi
done

test=$("(l(100)\/l(10))\/1 | bc -l")
echo $test
