#!/bin/bash
cd doc
i=10

echo Clearing the dist directory
rm -rf ../dist
mkdir -p ../dist

echo Resequencing files...
for f in *.md;
do
    mv "$f" "$i${f:2}" 2>/dev/null
    let "i=i+10"
done

stub1="pandoc --standalone --toc --metadata pagetitle="TMyMoney" --highlight-style pygments -c pandoc"
stub2=".css *.md --output "

function convert {
    echo Converting to $2...
    rm -f $1.$2
    ${stub1}$2${stub2}$1.$2
    echo Copying to dist directory
    cp $1.$2 ../dist/$1.$2
    cp pandoc$2.css ../dist
}
convert index html
convert tmymoney epub 

echo Setting up the local busybox server
cd ..
pkill -f "busybox httpd -p 4202 -h ./dist"
busybox httpd -p 4202 -h ./dist
echo Hugo site served at http://localhost:4202
